[package]
name = "yamlutils"
version = "0.1.0"
authors = ["john li <jli@circularly.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1"
serde_json = "1"
serde_yaml = "0.8"
structopt = "0.3"
